### ISSUE TITLE
View [scripts.airport_search] not found.

### ISSUE THREAD

**Issue by gefoxlu** [FSVAOS/CHFreeFlight#1]
Hello, I have installed your module but I get an error that it cannot find the "airport_search" script. Could you make that script available?

**Comment by BossOfGames** [comment]
I used the default file that comes with the default theme, which should auto-resolve.

Are you running the default theme?

I can release an update tonight which has the file baked into the module, just in case of issues like this.

**Comment by gefoxlu** [comment]
I have already managed to solve it, I had a theme from a previous version of phpvms and that is why the script did not appear.
